# Generated by Django 3.2.16 on 2022-11-04 01:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pollapp', '0002_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 1, 19, 32, 99504, tzinfo=utc)),
        ),
    ]
