# Generated by Django 3.2.16 on 2022-11-04 01:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pollapp', '0003_alter_vote_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 1, 20, 59, 420843, tzinfo=utc)),
        ),
    ]
